export const FETCH_IMAGE_REQUEST = 'FETCH_IMAGE_REQUEST';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const FETCH_IMAGE_FAILURE = 'FETCH_IMAGE_FAILURE';

export const UPDATE_SEARCH_TAGS = 'UPDATE_SEARCH_TAGS';

export const SET_THEME = 'SET_THEME';

export const TOGGLE_SETTINGS_MODAL = 'TOGGLE_SETTINGS_MODAL';
